### PR TITLE
Write to (compressed) HDF5

### PR DESCRIPTION
**Pull request by arnav-singhal**
Uses AMReX's HDF5 feature to write to HDF5 at runtime. Once https://github.com/AMReX-Codes/amrex/pull/4015 is merged, will also internally compress the HDF5 files using GZIP/ZLIB (currently set at level 6—could be adjusted). A (parallel) HDF5 installation is necessary; the conda environment on Perlmutter automatically loads it, else something like module load hdf5-parallel or module load cray-hdf5-parallel might be needed.

The chunk size used in compression is controlled by the environment variable HDF5_CHUNK_SIZE. We'll get it set up so that initializing the conda environment on Perlmutter should automatically set it to a reasonable value of 100,000—otherwise, AMReX uses a default of 1024 which is far too low. 

At chunk size of 100,000 and GZIP level of 6, for 180 days of Bay Area data, this improves space from about 47 GB to 533 MB, with negligible read/write time difference. 

Currently, the community-level data (used for plotting geographic graphs, for example) is stored at `pltxxxxx.h5` and the agent-level data is stored at `pltxxxxx/agents/agents.h5`; We may want to rename the community-level data file name for clarity.

The format of the data is different: we use the attributes of the files (file_variable.attrs in python) to see the labels of the components.

- For agent-level data, components are either stored as ints or reals. The int data is located at `file['level_0']['data:datatype=0']` and the real data is located at `file['level_0']['data:datatype=1']`.

Each agent has two extra int components (particle ID per CPU and CPU number) and two extra real components (x position and y position) which are stored in positions 0 and 1 of their respective datasets, and other components are labelled in the file's `int_component_x` or `real_component_x` attributes. 

The data is written agent-to-agent as a one-dimensional array, so a sensible way to deal with the data in python would be to store the int data in a numpy array by calling `int_data = file['level_0']['data:datatype=0'][()].reshape(-1, file['num_component_int'] + 2)`, for example, where each row contains a different agent's data, such that `int_data[:, 2]` is an array with the statuses of all agents.
- For community/tract-level data, each component is stored in a different dataset: `file['level_0']['data:datatype=x']` where we can find what the x'th component represents by looking at `file.attrs['component_x']` 

I've updated the movie-frame generating script to allow the use of this format, and I'm happy to help people get used to the layout.

### CODE REVIEW

**Comment by arnav-singhal** [comment]
(Sorry, closed this because I thought there was a bug in here but it was in the AMReX code.)
It seems there's a fairly significant runtime cost at the USA level, taking around 25 minutes to run a 50 day simulation (originally took around 8 minutes), while compressing total size from 551 GB to 25 GB. A lower compression level would probably alleviate this, but I guess it's user-dependent?

**Comment by atmyers** [comment]
Since this makes HDF5 a required dependency, we need to update the CI to install hdf5-parallel as part of the build process.

**Comment by arnav-singhal** [comment]
@atmyers What's the process for adding hdf5 to the CI? Is that something I should do or something you need to do?

**Comment by atmyers** [comment]
Hi @arnav-singhal - you could fix this as part of this pull request by modified the files that set up the GitHub CI. The files that install the dependencies are in `.github/workflows/dependencies/`. See [this](https://github.com/AMReX-Codes/ExaEpi/blob/development/.github/workflows/dependencies/dependencies_gcc10.sh) one for example. I think you just need to add a few lines to `sudo apt-get` the right hdf5 libraries there. We do in AMReX [here](https://github.com/AMReX-Codes/amrex/blob/dcb9cc0383dcc71e38dee9070574e325a812f8bf/.github/workflows/gcc.yml#L657).

**Comment by arnav-singhal** [comment]
The `static` non-`inline` header file function warning seems to be clang specific, so at least our other checks can hold in the meantime.

**Review by atmyers — APPROVED** [review]

**Comment by atmyers** [comment]
Thanks!

**Pull request merged**
